### ISSUE TITLE
TODO No. 1

### ISSUE THREAD

**Issue by psprint** [zdharma/zplugin#41]
From #30:
- [x] support completion-only SVN snippet (by `pick""`)
- [x] compile SVN snippets that are not `as"command"` (on install / update)
- [ ] decide whether to add request-compilation ice, implement
- [ ] update `compile --all` and `compile` to support snippets
- [ ] decide if `src` should obtain multiple file names and/or patterns, implement
- [ ] expose Curl (not wget, double-checked) complex-URL feature `../{file1,file2}`
- [ ] develop `repo created once every startup` idea
- [ ] add non-tar `*.gz` etc. support to `from"gh-r"`

From #31:
- [ ] command to delete all plugins and snippets that are not loaded or scheduled for dowload

From #33:
- [ ] add and document function to run `cdreplay` from `wait`-deferred plugin/snippet, from `atload` ice

Own:
- [ ] command `summon` to fetch saved plugin/snippet ice-mods, and obtain `zplugin ice ...` command at prompt
- [ ] guarantee `update --all` interrupted with Ctrl-C will exit cleanly

**Comment by SultanSGillani** [comment]
+1 on the #31 issue. It would be nice to have something similar to the vim-plug CleanAll function as noted [here](https://github.com/junegunn/vim-plug/blob/f1ad2d864ab43c56bf86ce01be9971f62bc14f6c/plug.vim#L144)

**Comment by psprint** [comment]
I think that I'll implement it today

**Comment by psprint** [comment]
It is done – new options `--all` which removes all snippets & plugins and `--clean` which removes currently not loaded snippets & plugins . Only the snippet removal doesn't always delete each unloaded snippet on `--clean`, as snippets share some directory structure and matching through glob is impossible – I'll rewrite it using a loop later. So will i update the docs.
